echo kerberos.test.com > /proc/sys/kernel/hostname

if [ ! -e /var/kerberos/krb5kdc/principal ]; then
	/usr/sbin/kdb5_util -r TEST.COM create -s
	kadmin.local -r TEST.COM -q "addprinc admin/admin"
	kadmin.local -r TEST.COM -q "addprinc kong"


	echo test using: kinit kong
fi
/etc/init.d/krb5kdc start
/etc/init.d/kadmin start

if [ ! -e /etc/http.keytab ]; then
	#apache stuff.
	# http://www.microhowto.info/howto/configure_apache_to_use_kerberos_authentication.html
	kinit admin/admin
	kadmin -p admin/admin -q "addprinc -randkey HTTP/kerberos.test.com"
	kadmin -p admin/admin -q "ktadd -k /etc/http.keytab HTTP/kerberos.test.com"
fi
